export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const CREATE_PROJECT_RESET = "CREATE_PROJECT_RESET";

export const ALL_PROJECTS_REQUEST = "ALL_PROJECTS_REQUEST";
export const ALL_PROJECTS_SUCCESS = "ALL_PROJECTS_SUCCESS";
export const ALL_PROJECTS_FAIL = "ALL_PROJECTS_FAIL";